opifer_content_api_content:
    path: /contents
    defaults: { _controller: OpiferContentBundle:Api/Content:index }
    methods: [GET]
    options:
        expose: true

opifer_content_api_content_ids:
    path: /contents/ids/{ids}
    defaults: { _controller: OpiferContentBundle:Api/Content:ids }
    methods: [GET]
    options:
        expose: true

opifer_content_api_content_view:
    path: /contents/{id}
    defaults: { _controller: OpiferContentBundle:Api/Content:view }
    methods: [GET]
    options:
        expose: true

opifer_content_api_content_delete:
    path: /contents/{id}
    defaults: { _controller: OpiferContentBundle:Api/Content:delete }
    methods: [DELETE]
    options:
        expose: true

opifer_content_api_directory:
    path: /directories
    defaults: { _controller: OpiferContentBundle:Api/Directory:index }
    methods: [GET]
    options:
        expose: true

opifer_content_api_layout:
    path: /layouts
    defaults: { _controller: OpiferContentBundle:Api/Layout:index }
    methods: [GET]
    options:
        expose: true

opifer_content_api_contenteditor_create_block:
    path: /contenteditor/createblock/{ownerId}/{rootVersion}
    defaults: { _controller: OpiferContentBundle:Api/ContentEditor:createBlock }
    methods: [POST]
    options:
        expose: true

opifer_content_api_contenteditor_move_block:
    path: /contenteditor/moveblock
    defaults: { _controller: OpiferContentBundle:Api/ContentEditor:moveBlock }
    methods: [POST]
    options:
        expose: true

opifer_content_api_contenteditor_view_block:
    path: /contenteditor/viewblock/{id}/{rootVersion}
    defaults: { _controller: OpiferContentBundle:Api/ContentEditor:viewBlock }
    methods: [GET]
    options:
        expose: true

opifer_content_api_contenteditor_remove_block:
    path: /contenteditor/removeblock/{id}/{rootVersion}
    defaults: { _controller: OpiferContentBundle:Api/ContentEditor:removeBlock }
    methods: [DELETE]
    options:
        expose: true

opifer_content_api_contenteditor_publish:
    path: /contenteditor/publish
    defaults: { _controller: OpiferContentBundle:Api/ContentEditor:publishBlock }
    methods: [POST]
    options:
        expose: true
