services:
    opifer.formblock.choice_field_block:
        class: 'Opifer\FormBlockBundle\Block\Service\ChoiceFieldBlockService'
        arguments: ['@opifer.content.block_renderer', '@opifer.form.form_manager', '%opifer_formblock.choice_field_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'choice_field' }

    opifer.formblock.form_block:
        class: 'Opifer\FormBlockBundle\Block\Service\FormBlockService'
        arguments: ['@opifer.content.block_renderer', '@opifer.eav.eav_manager', '@opifer.form.form_manager', '%opifer_formblock.form_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'form' }

    opifer.formblock.form_section_block:
        class: 'Opifer\FormBlockBundle\Block\Service\FormSectionBlockService'
        arguments: ['@opifer.content.block_renderer', '@opifer.form.form_manager', '%opifer_formblock.form_section_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'form_section' }

    opifer.formblock.form_progress_block:
        class: 'Opifer\FormBlockBundle\Block\Service\FormProgressBlockService'
        arguments: ['@opifer.content.block_renderer', '%opifer_formblock.form_progress_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'form_progress' }

    opifer.formblock.number_field_block:
        class: 'Opifer\FormBlockBundle\Block\Service\NumberFieldBlockService'
        arguments: ['@opifer.content.block_renderer', '@opifer.form.form_manager', '%opifer_formblock.number_field_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'number_field' }

    opifer.formblock.range_field_block:
        class: 'Opifer\FormBlockBundle\Block\Service\RangeFieldBlockService'
        arguments: ['@opifer.content.block_renderer', '@opifer.form.form_manager', '%opifer_formblock.range_field_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'range_field' }

    opifer.formblock.text_field_block:
        class: 'Opifer\FormBlockBundle\Block\Service\TextFieldBlockService'
        arguments: ['@opifer.content.block_renderer', '@opifer.form.form_manager', '%opifer_formblock.text_field_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'text_field' }

    opifer.formblock.date_field_block:
        class: 'Opifer\FormBlockBundle\Block\Service\DateFieldBlockService'
        arguments: ['@opifer.content.block_renderer', '@opifer.form.form_manager', '%opifer_formblock.date_field_block_configuration%']
        tags:
            - { name: 'opifer.content.block_service', alias: 'date_field' }
