opifer_content_formtype_angular:
    path: /formtype/angular
    defaults: { _controller: OpiferContentBundle:Backend/FormType:angular }
    options:
        expose: true

opifer_content_template_index:
    path: /template
    defaults: { _controller: OpiferContentBundle:Backend/Template:index }

opifer_content_template_editor:
    path: /template/editor/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Template:editor }

opifer_content_template_editor_view:
    path: /template/editor/view/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Template:editorView }

# Content

opifer_content_content_create:
    path: /content/create/{type}/{mode}
    defaults: { _controller: OpiferContentBundle:Backend/Content:create, type: 0, mode: simple }

opifer_content_content_details:
    path: /content/details/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Content:details, id: 0 }
    options:
        expose: true

opifer_content_content_duplicate:
    path: /content/duplicate/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Content:duplicate }
    options:
        expose: true

opifer_content_content_index:
    path: /content
    defaults: { _controller: OpiferContentBundle:Backend/Content:index }

opifer_content_content_type:
    path: /content/type/{type}
    defaults: { _controller: OpiferContentBundle:Backend/Content:type }
    requirements:
        type:  \d+

opifer_content_content_history:
    path: /content/history/{type}/{id}/{version}
    defaults: { _controller: OpiferContentBundle:Backend/Content:history, version: 0 }
    options:
        expose: true

# Contenteditor

opifer_content_contenteditor_design:
    path: /designer/{type}/{id}/{rootVersion}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:design, rootVersion: 0 }
    options:
        expose: true

opifer_content_contenteditor_edit_block:
    path: /contenteditor/editblock/{id}/{rootVersion}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:editBlock, rootVersion: 0 }
    options:
        expose: true

opifer_content_contenteditor_version_picker:
    path: /contenteditor/versionpicker/{id}/{current}/{published}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:versionPicker, current: 0, published: 0 }
    options:
        expose: true

opifer_content_contenteditor_view:
    path: /contenteditor/view/{type}/{id}/{version}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:view, version: 0 }
    options:
        expose: true

opifer_content_contenteditor_toc:
    path: /designer/toc/{type}/{id}/{version}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:toc, version: 0 }
    options:
        expose: true

# Block

opifer_content_block_shared:
    path: /content/shared
    defaults: { _controller: OpiferContentBundle:Backend/Block:shared }
    options:
        expose: true

opifer_content_block_shared_edit:
    path: /content/shared/edit/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Block:sharedEdit }
    options:
        expose: true

opifer_content_block_delete:
    path: /content/block/delete/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Block:delete}
    options:
        expose: true

# Content Types

opifer_content_contenttype_index:
    path: /contenttype
    defaults: { _controller: OpiferContentBundle:Backend/ContentType:index }

opifer_content_contenttype_create:
    path: /contenttype/create
    defaults: { _controller: OpiferContentBundle:Backend/ContentType:create }

opifer_content_contenttype_edit:
    path: /contenttype/edit/{id}
    defaults: { _controller: OpiferContentBundle:Backend/ContentType:edit }

opifer_content_contenttype_delete:
    path: /contenttype/delete/{id}
    defaults: { _controller: OpiferContentBundle:Backend/ContentType:delete }
