parameters:
    opifer.content.block_listener.class: Opifer\ContentBundle\EventListener\BlockListener
    opifer.content.content_list_value_provider.class: Opifer\ContentBundle\ValueProvider\ContentListValueProvider
    opifer.content.content_manager.default.class: Opifer\ContentBundle\Model\ContentManager
    opifer.content.content_router.class: Opifer\ContentBundle\Router\ContentRouter
    opifer.content.content_value_provider.class: Opifer\ContentBundle\ValueProvider\ContentValueProvider
    opifer.content.content_type_manager.class: Opifer\ContentBundle\Model\ContentTypeManager
    opifer.content.form.contentpicker_type.class: Opifer\ContentBundle\Form\Type\ContentPickerType
    opifer.content.form.gutter_collection_type.class: Opifer\ContentBundle\Form\Type\GutterCollectionType
    opifer.content.form.span_collection_type.class: Opifer\ContentBundle\Form\Type\SpanCollectionType
    opifer.content.form.content_list_picker_type.class: Opifer\ContentBundle\Form\Type\ContentListPickerType
#    opifer.content.block_adapter_type.class: Opifer\ContentBundle\Form\Type\BlockAdapterFormType
    opifer.content.twig.content_extension.class: Opifer\ContentBundle\Twig\ContentExtension
    opifer.content.block_manager.class: Opifer\ContentBundle\Block\BlockManager
    opifer.content.content_design_suite.class: Opifer\ContentBundle\Designer\ContentSuite
    opifer.content.template_design_suite.class: Opifer\ContentBundle\Designer\TemplateSuite
    opifer.content.block_content_environment.class: Opifer\ContentBundle\Environment\ContentEnvironment
    opifer.content.block_template_environment.class: Opifer\ContentBundle\Environment\TemplateEnvironment

services:
    opifer.content.content_manager.default:
        class: '%opifer.content.content_manager.default.class%'
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@form.factory'
            - '@opifer.eav.eav_manager'
            - '%opifer_content.content_class%'
            - '%opifer_eav.schema_class%'

    opifer.content.twig_analyzer:
        class: Opifer\ContentBundle\Environment\TwigAnalyzer
        arguments: ['@twig', '@templating.name_parser']

    # Serializer

    opifer.content.handler.serialization:
        class: Opifer\ContentBundle\EventListener\Serializer\ContentEventSubscriber
        arguments: ['@liip_imagine.cache.manager', '@router']
        tags:
            - { name: jms_serializer.event_subscriber }

    # Form types

    opifer.content.content_type:
        class: Opifer\ContentBundle\Form\Type\ContentType
        arguments: ['%opifer_content.content_class%']
        tags:
            - { name: form.type }

    opifer.content.content_parent_type:
        class: Opifer\ContentBundle\Form\Type\ContentParentType
        arguments: ['@opifer.content.content_manager']
        tags:
            - { name: form.type }

    # Router

    opifer.content.content_router:
        class: '%opifer.content.content_router.class%'
        arguments: ['@request_stack', '@opifer.content.content_manager']

    # Twig Extension

    opifer.content.twig.content_extension:
        class: '%opifer.content.twig.content_extension.class%'
        arguments:
            - '@twig'
            - '@fragment.handler'
            - '@opifer.content.content_manager'
            - '@service_container'
            - '@request_stack'
        tags:
            - { name: twig.extension }

    opifer.content.content_value_provider:
        class: '%opifer.content.content_value_provider.class%'
        tags:
            - { name: opifer.eav.value_provider, alias: content }

    opifer.content.content_list_value_provider:
        class: '%opifer.content.content_list_value_provider.class%'
        arguments: ['%opifer_content.content_class%']
        tags:
            - { name: opifer.eav.value_provider, alias: content_list }

    opifer.content.form.contentpicker_type:
        class: '%opifer.content.form.contentpicker_type.class%'
        arguments: ['@opifer.content.content_manager']
        tags:
            - { name: form.type }

    opifer.content.form.content_list_picker_type:
        class: '%opifer.content.form.content_list_picker_type.class%'
        arguments: ['@opifer.content.content_manager']
        tags:
            - { name: form.type }

    opifer.content.form.content_tree_picker_type:
        class: Opifer\ContentBundle\Form\Type\ContentTreePickerType
        arguments: ['@opifer.content.content_manager', '@opifer.content.navigation_block']
        tags:
            - { name: form.type }

    opifer.content.form.gutter_collection:
        class: '%opifer.content.form.gutter_collection_type.class%'
        tags:
            - { name: form.type }

    opifer.content.form.span_collection:
        class: '%opifer.content.form.span_collection_type.class%'
        tags:
            - { name: form.type }

    opifer.content.block_manager:
        class: '%opifer.content.block_manager.class%'
        arguments: ['@doctrine.orm.default_entity_manager']

    opifer.content.content_design_suite:
        class: '%opifer.content.content_design_suite.class%'
        arguments: ['@router', '@opifer.content.content_manager']

    opifer.content.template_design_suite:
        class: '%opifer.content.template_design_suite.class%'
        arguments: ['@router', '@doctrine.orm.default_entity_manager']

    opifer.content.block_content_environment:
        class: '%opifer.content.block_content_environment.class%'
        arguments: ['@doctrine.orm.default_entity_manager', '@opifer.content.block_manager', '@opifer.content.twig_analyzer']
        calls:
            - [setContentManager, ['@opifer.content.content_manager']]

    opifer.content.block_template_environment:
        class: '%opifer.content.block_template_environment.class%'
        arguments: ['@doctrine.orm.default_entity_manager', '@opifer.content.block_manager', '@opifer.content.twig_analyzer']

    opifer.content.block_listener:
        class: '%opifer.content.block_listener.class%'
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }

    # Content Types

    opifer.content.content_type_manager:
        class: '%opifer.content.content_type_manager.class%'
        arguments:
          - '@doctrine.orm.default_entity_manager'
          - '@opifer.eav.schema_manager'
          - '@opifer.content.content_manager'
          - '%opifer_content.content_type_class%'

    opifer.content.content_type_type:
        class: Opifer\ContentBundle\Form\Type\ContentTypeType
        arguments: ['%opifer_content.content_class%']
        tags:
            - { name: form.type }
