# Routing used by multiple bundles
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security_check:
    pattern: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    methods: [POST]

fos_user_security_logout:
    pattern: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

# Bazinga Translator Routing
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

# Opifer bundle routing

opifer_eav:
    resource: "@OpiferEavBundle/Resources/config/routing.yml"
    prefix:   /admin

opifer_eav_form_submit:
    pattern: /eav/form/submit/{valueId}
    defaults:
        _controller: OpiferEavBundle:Form:submit
    requirements:
        valueId: "\d+"
    methods: [POST]

opifer_rules_engine:
    resource: "@OpiferRulesEngineBundle/Resources/config/routing.yml"
    prefix:   /

opifer_redirect:
    resource: "@OpiferContentBundle/Resources/config/routing.yml"
    prefix: /admin/redirects

# API routes
opifer_content:
    resource: "@OpiferContentBundle/Resources/config/routing.yml"
    prefix:   /admin

opifer_media:
    resource: "@OpiferMediaBundle/Resources/config/routing.yml"
    prefix:   /admin

opifer_cms_home:
    pattern:  /
    defaults: { _controller: OpiferCmsBundle:Front/Page:home }
    options: {sitemap: true}

opifer_cms_auto_complete:
    path: /autocomplete/{alias}
    defaults: { _controller: OpiferCmsBundle:AutoComplete:query }
    options:
        expose: true

opifer_cms_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

opifer_cms_exception:
    resource: "@OpiferCmsBundle/Controller/Front/ExceptionController.php"
    type:     annotation

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

# Third party bundle routing fallbacks

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_change_password:
    pattern:  /change-password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }
    methods:  [GET,POST]

_opifer_admin:
    resource: "routing_admin.yml"
    prefix:   /admin
